
[[dependencies]]
  branch = "master"
  name = "github.com/gorilla/mux"

[[dependencies]]
  branch = "master"
  name = "github.com/knq/envcfg"

[[dependencies]]
  branch = "master"
  name = "github.com/rnd/kudu"

[[dependencies]]
  branch = "master"
  name = "github.com/urfave/negroni"

[[dependencies]]
  branch = "master"
  name = "google.golang.org/grpc"
